{% set name = "libuwebsockets" %}
{% set version = "20.51.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/uNetworking/uWebSockets/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 6794e7895eb8cc182024a0ae482a581eaa82f55f7cca53ae88b30738449f3cb9

build:
  number: 0
  # uwebsockets is a header-only library that uses usockets and zlib, so any user of it eventually links libusockets
  run_exports:
    - {{ pin_compatible('libusockets', max_pin='x.x.x') }}
    - {{ pin_compatible ('libzlib', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
    # This is just to provide FinduSockets.cmake, not needed at runtime
    - ycm-cmake-modules
  host:
    - libusockets
    - zlib

test:
  commands:
    - test -f $PREFIX/include/uWebSockets/App.h  # [unix]
    - if not exist %LIBRARY_INC%\\uWebSockets\App.h exit 1  # [win]

about:
  home: https://github.com/uNetworking/uWebSockets
  license: Apache-2.0
  license_file: LICENSE
  summary: Simple, secure & standards compliant web server library for the most demanding of applications

extra:
  recipe-maintainers:
    - traversaro
